// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://curgukttyfrhvwokjtxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1cmd1a3R0eWZyaHZ3b2tqdHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0Njg5OTIsImV4cCI6MjA2NTA0NDk5Mn0.Snzx_MdlRJDwF6k_mR07MtFQwKi8sA2ElbcdcGkcgjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);