// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxialbjxqqounloxxgoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4aWFsYmp4cXFvdW5sb3h4Z29pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTg1MzAsImV4cCI6MjA2NTU5NDUzMH0.MKm0vuobOAJakqtQePTL4qpvTECZe5_ZNdAkkGdwkV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);